// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nerpopmmojmawwquovvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5lcnBvcG1tb2ptYXd3cXVvdnZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMjcyNDEsImV4cCI6MjA2MzkwMzI0MX0.DmzlYSaatYSfQbkxgL9xIo3AdlXvokWmbCpsfWUCBoU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);